language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: hELcM23KBwhSR+4mAuDgihPs3QyeTnIAEERNUfc5Tjv0YrSImiJybQ9pRgmBszDxIaQPyXfHkFs/YyLDDbmBjUOdo3rkhtpnXQtUGHKNj7eXR7VTsFcDIf/zNmnpP3P1BKGAC7Vz33P6Rc3GtJ1saWAk2lWAgJqWrRmJOcz/qmgg8Hqm08ADl5dpIMxTkhRORnMnU0qKod27OaWb1mKW8jot0u3+gTicZvpVR7FCzOUrs1N3nKDc4AsVdW3JF+ReX6PVj+AoJsTyeZFdNtdTJ1PH4CodebkhZ/SIc7mAo4NBswi963ePaYKzOqrE7QcqkHB5xv3+jmSMfRyGB4T9KtPPjSSltUCiXPnXOiBXYA1ZixVG4yPKBEG+zhl8Sni1tC/PvuSejuFhTRUexS43oGBixHppyAdplbS1Lo4bW6jVKUU9rHxwRuj6vAObQDqPwAJ0mydpKBdRVm2hyEBySfFHcCkNXzEoK/s8T72ys1WTyToti5+X/pudSR0tupBv4CTUcJGXrt2tAezVcvqb1h8O5Wq6fLFpWbMTXeAR6dM65wnohEhR4Pau+b7i9kqKlioy/T4WzKbe8VRY7DuovEM9r0rRWxZgU+X4VEVnq5Y0+VLwmbOO7k7r4jHipJoyhtQSVNvec/JlESNjry3uCrIzHxTwbrDtc7eHvC4tWGI=
  app: ci-spring-boot
