language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: ci-spring-boot
  api_key:
    secure: dF1YBX049LH/o9bXBZsl9NzsBtC86+lF6TUTNI+W0hVmSv0G2OdcePT75VkZnls0B90faH+ZSUGOo2As9jO92PBBTuTwicTcVsiB6yRtQ0YOXUEOzdesCXl98V6YPK62em6Yx2iFtTJnb9NmuMfXwVP13Q9bBGi4CnPRMPXqvDs/O7+EaRIPXIvL5nijKlrTlhlLnip6KlqfkDt2DXuRFZyEUTqSfu7nTAbq+lcti09Xh5fgkTXkFJwImyBDfc+iagybXiCKOn/3eoVigbzlO0vjTUagNzDQGDSiYxPNwgRG2DH12DVSjszYhjFB0UIptVincrHpA2v2NHd7jGekiKYORgvtghle/vX4/GEpokj7LrA17O3yCYA8xbxDZCo9hZC/44qtb7xqi/8zNbtHhy5Wjm9sd81ojtfQ+yKzp9rv+zt5GDvutT7T5ndzqYihAkoQ3/PhZh/xU/1zJf/j9IhlLfC41mcE242OM+5H+96qs1TkTlaZA6ALi73ioVRHO00cE9evlGn09uUK6geVuINygLLjXTuxl+a6A8OigL7m2iXL9NmNn9NiJ9PKSyZ7fAiK8bgwRP/gO9fo0zhLPtNqMXPV5wG3agck3GVuJT45YQa/k/kS9tCdwp+IwAvQDrtUZpmq73YOGKRwKpR627wUPEhJHic9gHBH80BGGJs=
