language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: ci-spring-boot-revitbaby
  api_key:
    secure: J/y61CFxv8kvJ7E53BcBbZOn9QP0lmm0TiFAsRXHpRw7JqL2zK+p5ngcAnFQeZd5Nf9ouRq7dV2BcJKkjV2068vLdN4ZiZqj8h0A2rNAGZ3jGqaty8NLmPhewmJz4I9dPdpm+3a+F7hSrBJ0OtW3rUyVuurUr+vNh+G8IbzeH9nK7AdLibSZe1W1EYT7W5fLZ2NC1cyYf2gadWE/crFvjzoR2l5vBOZ6HRIGMmjP3IQOX/hR0gtT5CZOs+CEmEHBheyyyHPRv862jx4kdvEY80ZYvfwFYIhXAyRAKSkQ6B5bTfrJs8cilR+Aa2WqFt5j6XKkgrRYHztM+L5bRv7yUcsxjiV6f1Z+Ji+kOdJu4Tz+fRV/TV8lJzB2p6cotZRka9ucvoYaduf7KNTfkmo8k8gqyyRhYQ201n22d6aB82f8vS72YZdVJRbkvkZ4LSMwu6cdMZAq6hclVMEdTfitBw61fpms0aYZUyahevC9oPHHr8jsHtCvrYAURIAdYScjKeuGqqI54QP3JQswjX+3KcEcEdwjZdq3dHZbARAJgYgDf4araFLSs7EBwqy9N2agbrekqf/a23IozbqHWyqewdqXa8/j1IBhncEW/aH+Vay+HvZ4m+Q7vb3KF9+B/Q/C8XtasqUeGTrT/Xx6Ks/TMlZxxBPEU64LS8m3nk/g2O0=
